providers:
  discord:
    enabled: false
    webhookURL: "https://discordapp.com/api/webhooks/{webhook.id}/{webhook.token}"
    avatarURL: "https://i.imgur.com/HZfKC5p.png"
  rocketchat:
    enabled: false
    webhookURL: "https://<rocket-chat-server-here>/hooks/{token}"
    iconURL: "https://i.imgur.com/vfdpgpG.png"
  slack:
    enabled: false
    webhookURL: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
    iconURL: "https://i.imgur.com/vfdpgpG.png"
  smtp:
    enabled: false
    server: "smtp.gmail.com"
    port: "587"
    username: "optional-user@mail.com"
    password: "optional-pass"
    subject: "AWS News"
    footer: "Brought to you by <a href='https://github.com/circa10a/go-aws-news'>go-aws-news</a>"
    from: "mail@gmail.com"
    to:
      - "some.email@mail.com"
      - "some.other@mail.com"
    # customTemplate: path/to/template.html
  yammer:
    enabled: false
    APIURL: https://www.yammer.com/api/v1/messages.json
    groupID: 123456
    token: somesecrettext
    messageType: update
    title: AWS News

