name: Code Coverage
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -coverprofile=coverage.txt ./...
    - name: Codecov
      uses: actions/checkout@master